project:
  type: website

website:
  title: "AoC"
  sidebar:
    style: "floating"
    search: false
    contents:
    - 2025.qmd
    - 2024.qmd
  page-footer:
    center:
      - text: "Front page"
        href: index.qmd
      - text: "Source code"
        href: https://codeberg.org/RensOliemans/aoc-25
format:
  html:
    grid:
      body-width: 850px
      sidebar-width: 150px
    anchor-sections: true
    code-tools: true
    code-fold: show
    execute:
        eval: false
    theme:
        light: flatly
        dark: darkly
    toc: true
    reference-location: margin
    citation-location: margin
    highlight-style: github
execute:
  freeze: auto
